
#pragma once

// This file is autogenerated. Any edits will be lost after running the compiler tests to update the references
enum class BreakpointType
{
    None = 0,
    StepInto = 1,
    StepOver = 2,
    CodeLine = 3,
    Once = 4,
};
