
#pragma once

// This file is autogenerated. Any edits will be lost after running the compiler tests to update the references
enum class DebuggerCommand
{
    None = 0,
    Continue = 1,
    StepInto = 2,
    StepOver = 3,
    QueryStatus = 4,
    EnableDebugging = 5,
    DisableDebugging = 6,
    Break = 7,
};
