
#pragma once

// This file is autogenerated. Any edits will be lost after running the compiler tests to update the references
enum class DebuggerCommand
{
    None = 0,
    Continue = 1,
    StepInto = 2,
    StepOver = 3,
    StepOut = 4,
    QueryStatus = 5,
    EnableDebugging = 6,
    DisableDebugging = 7,
    Break = 8,
    SendLocals = 9,
    SendArguments = 10,
    SendEvaluationStack = 11,
    BreakOnExceptions = 12,
};
