
#pragma once

// This file is autogenerated. Any edits will be lost after running the compiler tests to update the references
enum class MethodFlags
{
    None = 0,
    Static = 1,
    Virtual = 2,
    SpecialMethod = 4,
    Void = 8,
    Ctor = 16,
    Abstract = 32,
    ExceptionClausesPresent = 64,
};
