
#pragma once

// This file is autogenerated. Any edits will be lost after running the compiler tests to update the references
enum class PinUsage
{
    None = 0,
    Gpio = 1,
    I2c = 2,
    Spi = 3,
    Pwm = 4,
    Uart = 5,
    AnalogIn = 6,
    AnalogOut = 7,
    Unknown = -1,
};
