
#pragma once

// This file is autogenerated. Any edits will be lost after running the compiler tests to update the references
enum class RuntimeState
{
    KeepAlive = 0,
    TaskTermination = 1,
};
